# Generated by Django 3.2.6 on 2023-04-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='deleted',
        ),
    ]
