# Generated by Django 4.1.6 on 2023-03-30 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issue', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'verbose_name_plural': 'Выдачи'},
        ),
        migrations.AlterField(
            model_name='issue',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_book', to='book.book'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
