# Generated by Django 3.2.6 on 2023-04-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_alter_issue_options_alter_issue_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='start_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
