# Generated by Django 3.2.6 on 2023-04-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_alter_issue_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
