# Generated by Django 3.2.6 on 2023-04-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_issue_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='deleted',
        ),
    ]
