# Generated by Django 3.2.6 on 2023-04-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_cleaned_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='deleted',
        ),
    ]
