# Generated by Django 4.1.6 on 2023-03-30 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0002_alter_establishment_options_alter_establishment_name'),
        ('studentclass', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Класс'},
        ),
        migrations.AlterField(
            model_name='class',
            name='establishment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_establishment', to='establishment.establishment', verbose_name='Класс'),
        ),
    ]
