# Generated by Django 4.1.6 on 2023-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Район'},
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Район'),
        ),
    ]
