# Generated by Django 3.2.6 on 2023-04-10 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locality', '0002_alter_locality_options_alter_locality_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='deleted',
        ),
    ]
