# Generated by Django 4.1.6 on 2023-03-11 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('contacts', models.TextField(blank=True, max_length=1000, null=True)),
                ('address', models.TextField(blank=True, max_length=1000, null=True)),
                ('requisites', models.TextField(blank=True, max_length=1000, null=True)),
                ('deleted', models.BooleanField(default=0)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='establishment_locality', to='locality.locality')),
            ],
        ),
    ]
