# Generated by Django 4.1.6 on 2023-03-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='establishment',
            options={'verbose_name': 'Учебное учреждение', 'verbose_name_plural': 'Учебное учреждение'},
        ),
        migrations.AlterField(
            model_name='establishment',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Учебное учреждение'),
        ),
    ]
